### ISSUE TITLE
Question: Which utility model is implemented by Amnesia?

### ISSUE THREAD

**Issue by prasser** [dTsitsigkos/Amnesia#11]
Dear Amnesia Developers,

I'm trying to understand which utility model / information loss model (or models) Amnesia is using when automatically anonymizing data? I took a look at the documentation and also at the code but wasn't able to find a concrete hint.

Thanks a lot!
Fabian

**Comment by Nikoc-dimako** [comment]
Dear Fabian,

Thanks for your feedback, Amnesia's ReST API uses parallel Flash algorithm in order to automatically anonymize the data. 
I updated the README.md,  thanks again for your contribution!

**Comment by prasser** [comment]
Thanks a lot for the quick reply, but this doesn't answer my question. Flash is a generic algorithm that can be used with different privacy models and different models for measuring utility / information loss. My question: which model for information loss / utility is used with Flash in Amnesia?

**Comment by mterrovitis** [comment]
Hi Fabian,

For k-anonymity we do not use an information loss model, since the choice of the best solution is left to the user. We present all possible solutions to the user, alongside with tools to explore the data, so they can choose the one that suits them best.

If the case of km-anonymity, the choice of the best solution is done by the algorithm (the solution space is too large for visualization) and we use the Normalized Certainty Penalty(NCP) metric to measure the information loss. The metric is explained in the corresponding paper https://web.imsi.athenarc.gr/~mter/papers/vldb2008.pdf.

**Comment by prasser** [comment]
Hi Manolis,

thanks - this perfectly answers my question! Closing this issue now...

Best regards
Fabian
