### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by eilmrein** [dTsitsigkos/Amnesia#6]
I just cloned the repo, configured the os variable and ran "mvn package". Ended up in multiple complaints (ERROR) about class Pair missing.
My setup is debian buster 64bit amd, openjdk 11.0.9.1 64bit, maven 3.6.0

What's wrong?

**Comment by Nikoc-dimako** [comment]
Good evening, 

Could you send me a screenshot about the whole tracing messages?

**Comment by eilmrein** [comment]
Standby for the weekend, I'll try to move back to JDK 8 - let's see if that fixes it. At least I got the backend running with jdk 8 and the jar file inside the zip, however, when I connect http to 8181, I get a mosty empty page reading only "/index.html"

**Comment by Nikoc-dimako** [comment]
Hello,
This repo contains the backend source code of Amnesia, unfortunately we are not able to upload the front-end module because the template and different structures are not open source thus it is logical when to connect to localhost:8181 to receive an empty .html page. Therefore, you can connect and  anonymize your data throw Amnesia's API as it is described in the README. If you want to run the whole application (backend and front-end) you can download the linux version from the main website of Amnesia [here](https://amnesia.openaire.eu/download.html) and just run "Amnesia.jar". As for the first issue Amnesia uses JavaFX so maybe the command line `sudo apt install openjfx` will fix the error. I apologise for the confusion in the next version of Amnesia anonymization tool we will remove the openfx module because as we can understand  it is not supported anymore by oracle's JDKs

**Comment by eilmrein** [comment]
Build worked with JDK 1.8
